### ISSUE TITLE
Migrations not working

### ISSUE THREAD

**Issue by bybilvanis** [Prometee/SyliusVIESClientPlugin#16]
I've followed your documentation to install the plugin and run the migrations but I get this output when I run:
`php bin/console doctrine:migrations:diff`

>   No changes detected in your mapping information.  
![Schermafbeelding 2020-01-29 om 23 36 41](https://user-images.githubusercontent.com/19476615/73403677-3f4fcc80-42f0-11ea-8213-3abf50c8ef86.png)

**Comment by Prometee** [comment]
There should be something wrong before this step, can you double check the installation and configuration process. Especially check that the plugin is well loaded, the classes are correctly filled and the mapping of your choice is present.

If you want to compare with your configuration check the content of the test app here : https://github.com/Prometee/SyliusVIESClientPlugin/tree/master/tests/Application

**Comment by bybilvanis** [comment]
I saw your comments about to have the entities in the Entity folder [here](https://github.com/Prometee/SyliusVIESClientPlugin/blob/master/UPGRADE-1.0.md).

I've sylius 1.6.5 and my Channel and Address entities are in Entity/Addressing and Entity/Channel folders can that be the reason?

**Comment by Prometee** [comment]
The second point "Then change the default Sylius model class" is absolutely required, all plugins which are altering the database are acting like this, and this part can't be done automatically.
