### ISSUE TITLE
Missing fields for billing for companies

### ISSUE THREAD

**Issue by gabiudrescu** [Prometee/SyliusVIESClientPlugin#25]
In the screenshot used in the readme, there is a field called „company”. I don't see it where it is implemented with this plugin.

Is the screenshot done on an app that has additional fields? Imo, that field it should be included in this plugin as well.

Also, the billing address form should contain more fields to fill in company data:
 - company name
 - company registration number 
 - bank
 - IBAN

In Romania, for example, these fields are mandatory to issue an invoice to a company. One can implement them explicitly in the billing address form and ask them from the user or use an API to provide them in the backend, based on the VIES number.

**Comment by Prometee** [comment]
I take those screenshot from the test env of this plugin so this field come from `sylius/sylius` : https://github.com/Sylius/Sylius/blob/4601734308b60a0d7092616ef073de1e61da476a/src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Address.orm.xml#L35
