### ISSUE TITLE
VIES Soap validation  not happening

### ISSUE THREAD

**Issue by gabiudrescu** [Prometee/SyliusVIESClientPlugin#28]
In the readme you are advertising VIES API validation - but I can't seem to find anything related to this in the source code.

**Comment by Prometee** [comment]
@gabiudrescu it's because the validation is not done in this plugin, but in the dependent bundle : https://github.com/Prometee/VIESClientBundle also dependending on a lib https://github.com/Prometee/VIESClient

**Comment by gabiudrescu** [comment]
@Prometee so, with this file https://github.com/Prometee/SyliusVIESClientPlugin/blob/master/src/Resources/config/validation/VATNumberAwareInterface.xml#L14 you are calling this class https://github.com/Prometee/VIESClientBundle/blob/master/Constraints/VatNumberValidator.php#L38 that is using this helper to call the soap ws: https://github.com/Prometee/VIESClient/blob/master/src/Helper/ViesHelper.php#L38

**Comment by Prometee** [comment]
Yes this is how it works because VIES webservice could be used elsewhere (other sf projects, put php project, etc...) and I like to separate things which can be separated

**Comment by gabiudrescu** [comment]
thanks for the info.
